<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-triptii111/blob/main/numpy_worksheet_triptii111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [2]:
# Write your code here:
print(np.__version__)


2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [3]:
# Write your code here:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [4]:
# Write your code here:
bool_arr = np.full((3, 3), True, dtype=bool)
# Alternative: bool_arr = np.ones((3, 3), dtype=bool)
print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [5]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Write your code here:
odd_arr = arr[arr % 2 != 0]
print(odd_arr)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [7]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Write your code here:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [9]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Write your code here:
out = np.where(arr % 2 != 0, -1, arr)
print("Modified:", out)
print("Original:", arr)

Modified: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original: [0 1 2 3 4 5 6 7 8 9]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [11]:
# Input — do not modify
arr = np.arange(10)

In [12]:
# Write your code here:
reshaped_arr = arr.reshape(2, -1)
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [13]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [14]:
# Write your code here:
v_stacked = np.vstack([a, b])
# Alternative: np.concatenate([a, b], axis=0)
print(v_stacked)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [15]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [16]:
# Write your code here:
h_stacked = np.hstack([a, b])
# Alternative: np.concatenate([a, b], axis=1)
print(h_stacked)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [17]:
# Input — do not modify
a = np.array([1, 2, 3])

In [18]:
# Write your code here:
pattern = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [19]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [20]:
# Write your code here:
common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [21]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [22]:
# Write your code here:
removed_items = np.setdiff1d(a, b)
print(removed_items)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [23]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
# Write your code here:
matching_positions = np.where(a == b)
print(matching_positions)

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [25]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [26]:
# Write your code here:
extracted = a[(a >= 5) & (a <= 10)]
print(extracted)

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [27]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [28]:
# Write your code here:
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [29]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [30]:
# Write your code here:
swapped_cols = arr[:, [0, 2, 1]]
print(swapped_cols)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [31]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [32]:
# Write your code here:
swapped_rows = arr[[0, 2, 1], :]
print(swapped_rows)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [33]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [34]:
# Write your code here:
reversed_rows = arr[::-1, :]
print(reversed_rows)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [35]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [36]:
# Write your code here:
reversed_cols = arr[:, ::-1]
print(reversed_cols)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [37]:
# Write your code here:
rand_arr_range = np.random.uniform(5, 10, size=(5, 3))
print(rand_arr_range)

[[7.23143483 5.59274603 6.58599384]
 [7.3621759  5.80761481 8.96730659]
 [6.24071722 9.65541106 5.30643813]
 [6.2036163  6.86714533 9.92604077]
 [9.23464088 9.22808464 6.35233601]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [38]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [39]:
# Write your code here:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.161 0.506 0.555]
 [0.619 0.16  0.872]
 [0.859 0.474 0.941]
 [0.457 0.549 0.284]
 [0.528 0.644 0.227]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [40]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [41]:
# Write your code here:
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [42]:
# Input — do not modify
a = np.arange(15)

In [43]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [44]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [45]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [46]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris_data[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [47]:
# Write your code here:
species = np.array([row[4] for row in iris_data])
# Alternative: species = iris_data[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [48]:
# Write your code here:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [49]:
# Write your code here:
sepal_length = iris_2d[:, 0]
mean_val = np.mean(sepal_length)
median_val = np.median(sepal_length)
std_val = np.std(sepal_length)
print(f"Mean: {mean_val}, Median: {median_val}, Std: {std_val}")

Mean: 5.843333333333334, Median: 5.8, Std: 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [50]:
# Write your code here:
sl_min, sl_max = sepal_length.min(), sepal_length.max()
sl_normalized = (sepal_length - sl_min) / (sl_max - sl_min)
print(sl_normalized[:5])

[0.222222 0.166667 0.111111 0.083333 0.194444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [51]:
# Write your code here:
exp_sl = np.exp(sepal_length)
softmax_score = exp_sl / np.sum(exp_sl)
print(softmax_score[:5])

[0.00222  0.001817 0.001488 0.001346 0.002008]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [52]:
# Write your code here:
p5 = np.percentile(sepal_length, 5)
p95 = np.percentile(sepal_length, 95)
print(f"5th Percentile: {p5}, 95th Percentile: {p95}")

5th Percentile: 4.6, 95th Percentile: 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [53]:
# Write your code here:
# Create a copy so we do not disrupt other variables unexpectedly
np.random.seed(100)
iris_2d_nan = iris_2d.copy()
i, j = iris_2d_nan.shape
iris_2d_nan[np.random.randint(0, i, 20), np.random.randint(0, j, 20)] = np.nan
print(iris_2d_nan[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 nan 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [54]:
# Write your code here:
sl_nan = iris_2d_nan[:, 0]
nan_count = np.isnan(sl_nan).sum()
nan_positions = np.where(np.isnan(sl_nan))
print(f"Number of missing values: {nan_count}")
print(f"Positions: {nan_positions}")

Number of missing values: 4
Positions: (array([14, 34, 79, 87]),)


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [55]:
# Write your code here:
# Using the original iris_2d to bypass NaN conflicts
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[condition]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [56]:
# Write your code here:
clean_rows = iris_2d_nan[~np.isnan(iris_2d_nan).any(axis=1)]
print(clean_rows[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [57]:
# Write your code here:
correlation_matrix = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])
correlation = correlation_matrix[0, 1]
print(f"Correlation: {correlation}")

Correlation: 0.8717541573048718


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [58]:
# Write your code here:
has_nan = np.isnan(iris_2d_nan).any()
print(f"Does it have missing values? {has_nan}")

Does it have missing values? True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [59]:
# Write your code here:
iris_replaced = iris_2d_nan.copy()
iris_replaced[np.isnan(iris_replaced)] = 0
print(iris_replaced[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 0.  1.4 0.2]
 [4.9 3.1 1.5 0.1]]


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [60]:
# Write your code here:
species_clean = iris_data[:, 4]
unique_vals, counts = np.unique(species_clean, return_counts=True)
print(dict(zip(unique_vals, counts)))

{b'Iris-setosa': np.int64(50), b'Iris-versicolor': np.int64(50), b'Iris-virginica': np.int64(50)}


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [61]:
# Write your code here:
petal_length = iris_2d[:, 2]
binned = np.digitize(petal_length, [0, 3, 5])
label_map = {1: 'small', 2: 'medium', 3: 'large'}
categorical_pl = np.array([label_map[x] for x in binned])
print(categorical_pl[:10])

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [62]:
# Write your code here:
petal_length = iris_2d[:, 2]
sepal_length = iris_2d[:, 0]
volume = (np.pi * petal_length * (sepal_length ** 2)) / 3
# Append the new column to iris_2d
iris_with_volume = np.hstack([iris_2d, volume.reshape(-1, 1)])
print(iris_with_volume[:5])

[[ 5.1       3.5       1.4       0.2      38.132652]
 [ 4.9       3.        1.4       0.2      35.200498]
 [ 4.7       3.2       1.3       0.2      30.072372]
 [ 4.6       3.1       1.5       0.2      33.23805 ]
 [ 5.        3.6       1.4       0.2      36.651914]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [63]:
# Write your code here:
np.random.seed(100)
species_list = iris_data[:, 4]
# Assign probabilities: setosa (0.5), versicolor (0.25), virginica (0.25)
probs = np.where(species_list == b'Iris-setosa', 0.5, 0.25)
probs = probs / probs.sum() # Normalize probabilities
sampled_indices = np.random.choice(len(species_list), size=20, p=probs)
print(species_list[sampled_indices])

[b'Iris-versicolor' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica'
 b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-virginica' b'Iris-setosa' b'Iris-virginica' b'Iris-setosa']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [64]:
# Write your code here:
setosa_mask = (iris_data[:, 4] == b'Iris-setosa')
# Pull petal lengths (Col 2) for setosa entries
setosa_pl = iris_2d[setosa_mask, 2]
unique_sorted = np.unique(setosa_pl)
second_largest = unique_sorted[-2]
print(f"Second largest petal length: {second_largest}")

Second largest petal length: 1.7


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [65]:
# Write your code here:
sorted_indices = np.argsort(iris_2d[:, 0])
sorted_iris = iris_2d[sorted_indices]
print(sorted_iris[:5])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [66]:
# Write your code here:
vals, counts = np.unique(iris_2d[:, 2], return_counts=True)
most_frequent = vals[np.argmax(counts)]
print(f"Most frequent value: {most_frequent}")

Most frequent value: 1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [67]:
# Write your code here:
petal_width = iris_2d[:, 3]
position = np.argwhere(petal_width > 1.0)[0][0]
print(f"First position index: {position}")

First position index: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [68]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [69]:
# Write your code here:
clipped_arr = np.clip(a, 10, 30)
print(clipped_arr)

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [70]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [71]:
# Write your code here:
top_5_idx = np.argsort(a)[-5:][::-1]
print(top_5_idx)

[15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [72]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [73]:
# Write your code here:
def get_row_counts(row):
    # Returns an array tracking value counts from 1 up to 10
    return np.bincount(row, minlength=11)[1:]

row_counts = np.array([get_row_counts(row) for row in arr])
print(row_counts)

[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [74]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [75]:
# Write your code here:
flat_array = np.concatenate(arr_2d)
print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.